### ISSUE TITLE
Error: Trying to store a string with len [449] in [ID] column but this column has a limit of [323]

### ISSUE THREAD

**Issue by eudoraleer** [roshchupkin/hase#4]
I was using hase.py to convert Plink format data into .h5 format data, and I have this error message after running hase.py:

```
Traceback (most recent call last):
  File "/home/lupan/GTex/REFERENCE/HASE/hase.py", line 158, in <module>
    G.plink2hdf5(out=args.out)
  File "/domus/h1/lupan/GTex/REFERENCE/HASE/hdgwas/converter.py", line 168, in plink2hdf5
    self.convert_probes()
  File "/domus/h1/lupan/GTex/REFERENCE/HASE/hdgwas/converter.py", line 112, in convert_probes
    complib='zlib',complevel=9, min_itemsize = 45)
  File "/sw/comp/python/2.7.15_rackham/lib/python2.7/site-packages/pandas/core/generic.py", line 1993, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "/sw/comp/python/2.7.15_rackham/lib/python2.7/site-packages/pandas/io/pytables.py", line 279, in to_hdf
    f(store)
  File "/sw/comp/python/2.7.15_rackham/lib/python2.7/site-packages/pandas/io/pytables.py", line 271, in <lambda>
    f = lambda store: store.append(key, value, **kwargs)
  File "/sw/comp/python/2.7.15_rackham/lib/python2.7/site-packages/pandas/io/pytables.py", line 987, in append
    **kwargs)
  File "/sw/comp/python/2.7.15_rackham/lib/python2.7/site-packages/pandas/io/pytables.py", line 1367, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)
  File "/sw/comp/python/2.7.15_rackham/lib/python2.7/site-packages/pandas/io/pytables.py", line 3946, in write
    **kwargs)
  File "/sw/comp/python/2.7.15_rackham/lib/python2.7/site-packages/pandas/io/pytables.py", line 3617, in create_axes
    raise e
ValueError: Trying to store a string with len [449] in [ID] column but
this column has a limit of [323]!
Consider using min_itemsize to preset the sizes on these columns
```

Can you guide me on this?

Thanks!

**Comment by roshchupkin** [comment]
It depends on your dataset. You have this error due to the fact that variant names in your .bim file are too long. HASE process this file chunk by chunk and  hdf5 file columns are made based on the max length from the first chunk. So if the max variant name in next chunk is longer you will get such error. 

Therefore,  long  story short, what you can do to fix it fast, in the file ./hdgwas/converter.py line 88, change the chunk size to "100000000" then HASE will convert the entire .bim at once. 

I will make a proper fix in the next version of HASE, but this should work for you now.

**Comment by eudoraleer** [comment]
It worked perfectly! Thank you!!

**Comment by eudoraleer** [comment]
> It depends on your dataset. You have this error due to the fact that variant names in your .bim file are too long. HASE process this file chunk by chunk and hdf5 file columns are made based on the max length from the first chunk. So if the max variant name in next chunk is longer you will get such error.
> 
> Therefore, long story short, what you can do to fix it fast, in the file ./hdgwas/converter.py line 88, change the chunk size to "100000000" then HASE will convert the entire .bim at once.
> 
> I will make a proper fix in the next version of HASE, but this should work for you now.

It worked perfectly! Thank you!!
