### ISSUE TITLE
error messages: allow_pickle=False

### ISSUE THREAD

**Issue by r-mustafa** [roshchupkin/hase#8]
Hi,
I got this new error message below, which was never happened before. This error appears both when running regression mode and combining npy files into results.csv.

/etc/profile.d/passwd_expiry.sh: line 20: [: -31: unary operator expected
/etc/profile.d/passwd_expiry.sh: line 27: [: 34: unary operator expected
Traceback (most recent call last):
File "/home/rmustafa/hase//hase.py", line 250, in 
mapper.load(args.mapper)
File "/home/rmustafa/hase/hdgwas/tools.py", line 513, in load
self.keys=np.load(os.path.join(keys[0]) )#TODO (middle) not safety to load only one file
File "/home/rmustafa/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 447, in load
pickle_kwargs=pickle_kwargs)
File "/home/rmustafa/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 696, in read_array
raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

I think this is due to recent changes in the numpy library which now requires allow_pickle=True to be explicitly written when loading the objects, so adding allow_pickle=True solves the problem, and this corresponds to the hdgwas/tools.py, hdgwas/data.py (and let me know if I miss anything!).
Thank you.

**Comment by CAWarmerdam** [comment]
Hi,
I have also gotten this error message. Since Numpy version 1.16.3 the allow_pickle is set to False by default. Adding the allow_pickle=True in places will indeed solve this issue. For now I am using Numpy version 1.16.2 to circumvent the problem.
